# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # scrapper
  - package-ecosystem: "npm"
    directory: "/scrapper"
    schedule:
      interval: "weekly"
    groups:
      production-version-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      production-security-dependencies:
        applies-to: security-updates
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
  # oapi
  - package-ecosystem: "npm"
    directory: "/oapi"
    schedule:
      interval: "weekly"
    groups:
      production-version-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      production-security-dependencies:
        applies-to: security-updates
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
  # frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      production-version-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      production-security-dependencies:
        applies-to: security-updates
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
  # imaker
  - package-ecosystem: "npm"
    directory: "/imaker"
    schedule:
      interval: "weekly"
    groups:
      production-version-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      production-security-dependencies:
        applies-to: security-updates
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
  # snpublisher
  - package-ecosystem: "npm"
    directory: "/snpublisher"
    schedule:
      interval: "weekly"
    groups:
      production-version-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      production-security-dependencies:
        applies-to: security-updates
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
